# Sidebar navigation

- label: 'Course information'
  link: '/overview'
- label: 'Schedule'
  link: '/schedule'
- label: 'Reading'
  link: '/reading'
- label: 'Learning activities and resources'
  link: '/online'
- label: 'Assignment submission'
  link: '/assignment-format'
- label: 'Evaluation methods'
  link: '/evaluation'
- label: 'Important university and faculty policies'
  link: '/policies'
